name: Build and push SpotMap to Azure Web App

on: []

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: "SpotMap"
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "22.14.0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "yarn install and build"
        run: |
          yarn install
          yarn
          yarn build

      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Azure logout
      - name: logout
        run: |
          az logout
