name: Build and push SpotMap to Azure Web App

on: []

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: "SpotMap"
  AZURE_WEBAPP_PACKAGE_PATH: "build.zip"
  NODE_VERSION: "18.19.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "yarn install, build, and test"
        run: |
          yarn install
          yarn
          yarn build

      - name: "Archive production artifacts"
        run: zip -r build.zip build

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
    needs: build
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout
